---
  root: true

  env:
    node: true
  
  extends:
    - plugin:vue/recommended
    - '@vue/eslint-config-prettier'
  
  rules:
    vue/require-default-prop: off
    no-console: off
    vue/v-bind-style: off
    vue/v-on-style: off
    vue/no-v-html: off
    no-unused-vars: off

    # Use single quotes wherever possible
    quotes:
      - error
      - single
      - avoidEscape: true
    
    # No semicolons at the end of lines
    semi:
      - error
      - never
  
  parserOptions:
    parser: babel-eslint
  
  globals:
    location: true
    document: true
    window: true
    GLOBAL: true
